### ISSUE TITLE
replace-part instead of replaceable

### ISSUE THREAD

**Issue by mredl** [MisterGoodcat/good-aurelia-components#1]
Hi!
In your demos your are showing how to replace the item-template, but 'replaceable" is not valid any more. you should use 'replace-part' like 
`<template replace-part="suggestion-item-template">`

**Comment by MisterGoodcat** [comment]
Hi Matthias,

the replaceable attribute is still required for some use cases, in particular those when you want to have item templates replaced (i.e. in repeaters). That's the case in all of my demos.

See this post for an explanation what use cases still require "replaceable": http://blog.aurelia.io/2016/06/08/getting-prepared-for-aurelia-1-0-0-rc/

See the confirmation here that "replaceable" needed to be put back into Aurelia for these use cases, and is still valid (and the only working option for repeaters) up to this day: https://github.com/aurelia/templating/issues/70#issuecomment-238402657

Hope this helps.

**Comment by MisterGoodcat** [comment]
In fact, I did upgrade all dependencies to their latest versions (just pushed the commit), and everything's still working as expected.

**Comment by mredl** [comment]
Thanks!
Very interesting. I'm also on the latest bits and tried with custom templates and it has failed until i changed from replaceable to "replace-part"

in your component its still
` <template replaceable part="suggestion-item-template">
            <div class="gac-suggestion-item ${item.isHighlighted ? 'gac-suggestion-item-highlighted' : ''}">${item.value}</div>
          </template>`

but in my viewmodel I had to change to
` <template replace-part="suggestion-item-template">
                    <div class="gac-suggestion-item ${item.isHighlighted ? 'gac-suggestion-item-highlighted' : ''}">${item.value.custNo}: ${item.value.nameByLaw}, ${item.value.address.zipCode}-${item.value.address.location}</div>
                  </template>`

**Comment by MisterGoodcat** [comment]
Sorry, I somehow missed that you responded.

I see the problem now (but there really is none): on the providing side of things you have to use "replaceable", to indicate that you offer consumers of your component to replace details. The value of "part" determines what name consumers have to provide to replace this particular detail. 

On the consuming side you then have to specify this part name with the "replace-part" attribute.

So, all good and both sides of the code (mine and yours) are correct and required like that. Take a look at the demo page included in my repository, it also uses "replace-part" on the consuming side of things to specify the custom template part. Example: https://github.com/MisterGoodcat/good-aurelia-components/blob/master/src/src/demo/auto-complete-demo.html#L81
